#page title
page_title                                : Maplocs Cycling Route Planner                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=abhiank.maplocs                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Maplocs Cycling Route Planner                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The best cycling route planner you'll find

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : 
your_link                                 : https://emilbaehr.com                     
your_city                                 : India                                
email_address                             : maplocs@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Easy and Convenient Route building for Cycling
    description                           : Built optimised for mobile experience, Maplocs has been built by passionate cyclists themselves who wanted to solve the problem of exploring and finding.
    fontawesome_icon_name                 : magic
    
  - title                                 : Accurate Routes
    description                           : Maplocs is powered by OpenRouteService which provides highly optimised and accurate routes for mountain bikes, road bikes, regular bikes and even cars. 
    fontawesome_icon_name                 : mobile

  - title                                 : Know exactly how much climb to expect
    description                           : Maplocs shows elevation profile of the entire route in one very easy to access view. You can see total elevation gain and loss. Additionally on touch of.
    fontawesome_icon_name                 : play-circle

  - title                                 : Powerful route building tools and options
    description                           : Maplocs can has been built with focus only on easy route building and planning. We have paid enormous attention to making it the best cycling app for route building.
    fontawesome_icon_name                 : sync

  - title                                 : Beautiful Cycling Maps
    description                           : You can choose from a variety of Maps on Maplocs - Google Satellite, Hybrid or Terrain maps which also show live traffic.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Unlock the power of GPX
    description                           : We have embraced the GPX standard to create and share tracks and routes. On Maplocs you can export your routes in GPX format to be used in Garmins.
    fontawesome_icon_name                 : star

  - title                                 : Send directly to Garmin and Wahoo
    description                           : We love our Garmin Edge as much you do so we added the functionality to send your routes directly to the Garmin app from the app.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Your routes always with you
    description                           : Doesn't matter if you're bike touring in Europe, crossing the Hardknott Pass in UK or cycling the great MTB Divide across USA, your routes will always be available.
    fontawesome_icon_name                 : link

  - title                                 : More Features Coming Soon
    description                           : Weather, import gpx, see elevation at point, etc
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown